### ISSUE TITLE
Latitude and Longitude 

### ISSUE THREAD

**Issue by leandroc** [tonyduanesmith/react-apple-mapkitjs#3]
Hi,

I'm giving the right latitude and longitude from Brasilia to `<AppleMaps longitude={-47.93} latitude={-15.78} />` and `<Annotation longitude={-47.93} latitude={-15.78} />`, but the position on map are wrong:

![image](https://user-images.githubusercontent.com/1707493/56931080-2c843f00-6ab5-11e9-8967-ded10dc10413.png)

I tried to change the props (latitude => longitude, vice-e-versa) and then it showed me the right result:

![image](https://user-images.githubusercontent.com/1707493/56931187-943a8a00-6ab5-11e9-9db6-213d6663848d.png)

Looking in the source code, i found that you made a mistake (or maybe Apple changed) in the parameters of `mapkit.Coordinate(longitude, latitude)` ([AppleMaps.js#L184](https://github.com/tonyduanesmith/react-apple-mapkitjs/blob/master/src/lib/AppleMaps.js#L184)). The right order is `mapkit.Coordinate(latitude, longitude)` [Mapkit Docs](https://developer.apple.com/documentation/mapkitjs/mapkit/coordinate/2973854-mapkit_coordinate).

**Comment by lucidlemon** [comment]
Jesus Christ!
Thanks! I thought i was going mad
